# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/main_design/main_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_zynq_ultra_ps_e_0_0/main_design_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==main_design_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_AXI_LITE_source_v1_0_0_0/main_design_AXI_LITE_source_v1_0_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_AXI_LITE_source_v1_0_0_0 || ORIG_REF_NAME==main_design_AXI_LITE_source_v1_0_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_ps8_0_axi_periph_0/main_design_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_ps8_0_axi_periph_0 || ORIG_REF_NAME==main_design_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rst_ps8_0_250M_0/main_design_rst_ps8_0_250M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_rst_ps8_0_250M_0 || ORIG_REF_NAME==main_design_rst_ps8_0_250M_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_pc_0/main_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_pc_0 || ORIG_REF_NAME==main_design_auto_pc_0} -quiet] -quiet

# XDC: bd/main_design/main_design_ooc.xdc
