@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Jan 10 12:58:52 +0900 2023
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/baba/Desktop/LSI_template/tb_behav1.wcfg -view C:/Users/baba/Desktop/LSI_template/fifoa.wcfg -view C:/Users/baba/Desktop/LSI_template/ram_adresssyusei.wcfg -log simulate.log"
call xsim  tb_behav -key {Behavioral:sim_1:Functional:tb} -tclbatch tb.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/baba/Desktop/LSI_template/tb_behav1.wcfg -view C:/Users/baba/Desktop/LSI_template/fifoa.wcfg -view C:/Users/baba/Desktop/LSI_template/ram_adresssyusei.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
